@baseUri=http://localhost:8023/api
# @baseUri=https://melodis.co/api

### update songs
POST {{baseUri}}/process/update-songs
Content-Type: application/json

{
   
}

### fetch song
POST {{baseUri}}/process/fetch-song
Content-Type: application/json

{
   "uuid": "f81be5c0-3de9-4940-95e1-cfb780d3aa5e"
}

### fetch trending songs
POST {{baseUri}}/process/fetch-trending-songs
Content-Type: application/json

{
   "page": 1
}

### fetch latest songs
POST {{baseUri}}/process/fetch-latest-songs
Content-Type: application/json

{
   "page": 1
}

### get random songs
POST {{baseUri}}/get-random-songs
Content-Type: application/json

{
   "page": 1,
   "limit": 3
}


### gen music
POST {{baseUri}}/gen-song
Content-Type: application/json

{
    "description": "a hip-pop song about a beautiful lady.",
    "style": "hip-pop",
    "lyric": "",
    "title": "" 
}

### get favorite song
POST {{baseUri}}/get-favorite-song
Content-Type: application/json

{
   "song_uuid": "f81be5c0-3de9-4940-95e1-cfb780d3aa5e"
}